# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Post.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nPost.proto\x12\x06reddit\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x01\n\x04Post\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x05\x12 \n\x05state\x18\x05 \x01(\x0e\x32\x11.reddit.PostState\x12\x34\n\x10publication_date\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\tvideo_url\x18\x07 \x01(\tH\x00\x12\x13\n\timage_url\x18\x08 \x01(\tH\x00\x42\x07\n\x05media*2\n\tPostState\x12\x0b\n\x07PNORMAL\x10\x00\x12\x0b\n\x07PLOCKED\x10\x01\x12\x0b\n\x07PHIDDEN\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Post_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSTSTATE']._serialized_start=263
  _globals['_POSTSTATE']._serialized_end=313
  _globals['_POST']._serialized_start=56
  _globals['_POST']._serialized_end=261
# @@protoc_insertion_point(module_scope)
