# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Reddit.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import User_pb2 as User__pb2
import Post_pb2 as Post__pb2
import Comment_pb2 as Comment__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cReddit.proto\x12\x06reddit\x1a\nUser.proto\x1a\nPost.proto\x1a\rComment.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"c\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x13\n\tvideo_url\x18\x03 \x01(\tH\x00\x12\x13\n\timage_url\x18\x04 \x01(\tH\x00\x42\x07\n\x05media\"2\n\x0fVotePostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0e\n\x06upvote\x18\x02 \x01(\x08\"!\n\x0eGetPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"t\n\x14\x43reateCommentRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\x12\x19\n\x11parent_comment_id\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\"8\n\x12VoteCommentRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x0e\n\x06upvote\x18\x02 \x01(\x08\"3\n\x15GetTopCommentsRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\t\n\x01n\x18\x02 \x01(\x05\"8\n\x13TopCommentsResponse\x12!\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x0f.reddit.Comment\";\n\x1a\x45xpandCommentBranchRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\t\n\x01n\x18\x02 \x01(\x05\":\n\x15\x43ommentBranchResponse\x12!\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x0f.reddit.Comment2\xce\x03\n\rRedditService\x12\x35\n\nCreatePost\x12\x19.reddit.CreatePostRequest\x1a\x0c.reddit.Post\x12\x31\n\x08VotePost\x12\x17.reddit.VotePostRequest\x1a\x0c.reddit.Post\x12/\n\x07GetPost\x12\x16.reddit.GetPostRequest\x1a\x0c.reddit.Post\x12>\n\rCreateComment\x12\x1c.reddit.CreateCommentRequest\x1a\x0f.reddit.Comment\x12:\n\x0bVoteComment\x12\x1a.reddit.VoteCommentRequest\x1a\x0f.reddit.Comment\x12L\n\x0eGetTopComments\x12\x1d.reddit.GetTopCommentsRequest\x1a\x1b.reddit.TopCommentsResponse\x12X\n\x13\x45xpandCommentBranch\x12\".reddit.ExpandCommentBranchRequest\x1a\x1d.reddit.CommentBranchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Reddit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEPOSTREQUEST']._serialized_start=124
  _globals['_CREATEPOSTREQUEST']._serialized_end=223
  _globals['_VOTEPOSTREQUEST']._serialized_start=225
  _globals['_VOTEPOSTREQUEST']._serialized_end=275
  _globals['_GETPOSTREQUEST']._serialized_start=277
  _globals['_GETPOSTREQUEST']._serialized_end=310
  _globals['_CREATECOMMENTREQUEST']._serialized_start=312
  _globals['_CREATECOMMENTREQUEST']._serialized_end=428
  _globals['_VOTECOMMENTREQUEST']._serialized_start=430
  _globals['_VOTECOMMENTREQUEST']._serialized_end=486
  _globals['_GETTOPCOMMENTSREQUEST']._serialized_start=488
  _globals['_GETTOPCOMMENTSREQUEST']._serialized_end=539
  _globals['_TOPCOMMENTSRESPONSE']._serialized_start=541
  _globals['_TOPCOMMENTSRESPONSE']._serialized_end=597
  _globals['_EXPANDCOMMENTBRANCHREQUEST']._serialized_start=599
  _globals['_EXPANDCOMMENTBRANCHREQUEST']._serialized_end=658
  _globals['_COMMENTBRANCHRESPONSE']._serialized_start=660
  _globals['_COMMENTBRANCHRESPONSE']._serialized_end=718
  _globals['_REDDITSERVICE']._serialized_start=721
  _globals['_REDDITSERVICE']._serialized_end=1183
# @@protoc_insertion_point(module_scope)
